<?php

/**
 * Autogenerated base class for the Overlay model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Overlay.php file.
 *
 * @module Overlay
 */
/**
 * Base class for the Overlay model
 * @class Base_Overlay
 */
abstract class Base_Overlay
{
	/**
	 * The list of model classes
	 * @property $table_classnames
	 * @type array
	 */
	static $table_classnames = array (
  0 => 'Overlay_Counter',
);

	/**
     * This method calls Db.connect() using information stored in the configuration.
     * If this has already been called, then the same db object is returned.
	 * @method db
	 * @return {iDb} The database object
	 */
	static function db()
	{
		return Db::connect('Overlay');
	}

	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Overlay';
	}
};